---
- name: Install required Ansible collections
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Install cisco.ios collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install cisco.ios
      register: cisco_ios_install
      changed_when: "'Skipping' not in cisco_ios_install.stdout"

    - name: Output result of cisco.ios installation
      ansible.builtin.debug:
        msg: "{{ cisco_ios_install.stdout }}"

    - name: Install ansible.netcommon collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install ansible.netcommon
      register: netcommon_install
      changed_when: "'Skipping' not in netcommon_install.stdout"

    - name: Output result of ansible.netcommon installation
      ansible.builtin.debug:
        msg: "{{ netcommon_install.stdout }}"
