---
- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: Install required Ansible collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install ansible.netcommon cisco.ios

    - name: List all installed Ansible collections
      ansible.builtin.shell:
        cmd: ansible-galaxy collection list
      register: collections_output

    - name: Output installed collections
      ansible.builtin.debug:
        msg: "{{ collections_output.stdout }}"

    - name: Hello Message
      ansible.builtin.debug:
        msg: "Hello World!"