---
- name: Add network-admin user to NX-OS switch
  hosts: all
  gather_facts: no
  collections:
    - cisco.nxos

    - name: Add user with network-admin role
      when: nxos_password != confirm_password
      cisco.nxos.nxos_user:
        name: "{{ nxos_username }}"
        configured_password: "{{ nxos_password }}"
        role: network-admin
        state: present

    - name: Save configuration to startup-config
      cisco.nxos.nxos_config:
        save_when: modified