---
- name: Add network-admin user to NX-OS switch
  hosts: all
  gather_facts: false
  collections:
    - cisco.nxos
    - community.general

  vars:
    # These variables will be populated from the AWX survey
    nxos_username: "{{ username }}"
    nxos_password: "{{ password }}"

  tasks:
    - name: Ensure user exists with network-admin role
      nxos_user:
        name: "{{ nxos_username }}"
        configured_password: "{{ nxos_password }}"
        role: network-admin
        state: present

    - name: Display the provided password
      debug:
        msg: "The password for user {{ nxos_username }} is {{ nxos_password }}"
