---
- name: Remove specified user from NX-OS switch and log the action
  hosts: all
  gather_facts: no
  collections:
    - cisco.nxos

  tasks:
    - name: Ensure the user is absent
      cisco.nxos.nxos_user:
        name: "{{ nxos_user_to_remove }}"
        state: absent

    - name: Save configuration to startup-config
      cisco.nxos.nxos_config:
        save_when: modified