---
- name: Add user to Cisco switches with privilege level 15
  hosts: all
  gather_facts: no

  tasks:
    - name: Add user to the switch
      ios_config:
        lines:
          - username {{ username }} privilege 15 secret {{ password }}

