---
- name: Remove user from NX-OS switch
  hosts: all
  gather_facts: no

  tasks:
    - name: Ensure the user is absent
      cisco.nxos.nxos_user:
        name: "{{ nxos_user_to_remove }}"
        state: absent

    - name: Save configuration to startup-config
      cisco.nxos.nxos_config:
        save_when: modified
