---
- name: Retrieve current time from NTP server 2
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Ensure ntpdate is installed on Debian-based systems
      ansible.builtin.apt:
        name: ntpdate
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Ensure ntpdate is installed on RedHat-based systems
      ansible.builtin.yum:
        name: ntpdate
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Query NTP server for current time
      ansible.builtin.command: ntpdate -q pool.ntp.org
      register: ntp_output

    - name: Display current time from NTP server
      ansible.builtin.debug:
        msg: "{{ ntp_output.stdout }}"
