---
- name: Run show version on Cisco devices
  hosts: 192.168.1.159
  tasks:
    - name: Run show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: show_version_output

    - name: Display output
      ansible.builtin.debug:
        msg: "{{ show_version_output }}"