---
- name: Cisco show version example
  hosts: all
  tasks:
    - name: run show version
      ios_command:
        commands: show version | incl Version
      register: output

    - name: print output
      debug:
        var: output.stdout_lines